[package]
name = "pge-learn-universe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
olc_pixel_game_engine = "0.6.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
